// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7xhsVfbk8aB9HQdBLU1aRDUG9bZ6QflE',
    appId: '1:74513211252:web:a90975ecd42f579f991621',
    messagingSenderId: '74513211252',
    projectId: 'chateasy-2e3a6',
    authDomain: 'chateasy-2e3a6.firebaseapp.com',
    storageBucket: 'chateasy-2e3a6.appspot.com',
    measurementId: 'G-ELLZ99EYQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWr2SV_jS28LeafAb4qX1n40y57Jxxfzs',
    appId: '1:74513211252:android:8630b19768373e65991621',
    messagingSenderId: '74513211252',
    projectId: 'chateasy-2e3a6',
    storageBucket: 'chateasy-2e3a6.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7xhsVfbk8aB9HQdBLU1aRDUG9bZ6QflE',
    appId: '1:74513211252:web:4cd96aba34a52e4d991621',
    messagingSenderId: '74513211252',
    projectId: 'chateasy-2e3a6',
    authDomain: 'chateasy-2e3a6.firebaseapp.com',
    storageBucket: 'chateasy-2e3a6.appspot.com',
    measurementId: 'G-Z7QQDNY1ZY',
  );
}
